### PR TITLE
Code for Insertion Sort added

### PR DESCRIPTION
**Pull request by Pranit5895**

### CODE REVIEW

**Comment by AkshatGoyal1018** [comment]
@Pranit5895 , You pasted the same as geeksforgeeks sorry these kind of codes are not accepted here. I want everything from your own nothing copy pasted.

**Review by AkshatGoyal1018 — COMMENTED** [review]
Sorry! I can't accept this copy pasted code. Do something yourself then I will see if I wanna consider it.

**Review by AkshatGoyal1018 — COMMENTED** [review]
Nicely done Pranit . I just need 2 more changes and you will be good to go 👍 .

**Review by AkshatGoyal1018 — CHANGES_REQUESTED** [review]
1. Indentation (very important for a programmer)
2. Writing main before the functions not a good practice .

**Review by PHAGUN-JAIN — APPROVED** [review]

**Pull request merged**
